### ISSUE TITLE
deselectMany error

### ISSUE THREAD

**Issue by richardshergold** [briebug/ngrx-auto-entity#60]
I could well be doing this wrong but after I make a call in my facade to selectMany like this

`this.selectMany([item])`

which seems to work and leaves a single value in **currentEntitiesKeys** of this:

`100000080_organisations-email_592913`

If I then try to call deselectMany passing across the same item in the array like this:

`this.deselectMany([item])`

I get an error of:

`100000080_organisations-email_592913 is not a function`

Error Log:

```
ERROR TypeError: 100000080_organisations-email_592913 is not a function
    at Array.some (<anonymous>)
    at http://localhost:8100/vendor.js:89104:49
    at Array.filter (<anonymous>)
    at autoEntityReducer (http://localhost:8100/vendor.js:89100:155)
    at http://localhost:8100/vendor.js:89176:16
    at http://localhost:8100/vendor.js:103927:20
    at computeNextEntry (http://localhost:8100/vendor.js:103092:21)
    at recomputeStates (http://localhost:8100/vendor.js:103126:15)
    at http://localhost:8100/vendor.js:103412:26
    at ScanSubscriber.StoreDevtools.liftedAction$.pipe.Object.state [as accumulator] (http://localhost:8100/vendor.js:103441:38)
    at ScanSubscriber.push../node_modules/rxjs/_esm5/internal/operators/scan.js.ScanSubscriber._tryNext (http://localhost:8100/vendor.js:128257:27)
    at ScanSubscriber.push../node_modules/rxjs/_esm5/internal/operators/scan.js.ScanSubscriber._next (http://localhost:8100/vendor.js:128250:25)
    at ScanSubscriber.push../node_modules/rxjs/_esm5/internal/Subscriber.js.Subscriber.next (http://localhost:8100/vendor.js:121614:18)
    at WithLatestFromSubscriber.push../node_modules/rxjs/_esm5/internal/operators/withLatestFrom.js.WithLatestFromSubscriber._next (http://localhost:8100/vendor.js:130594:34)
    at WithLatestFromSubscriber.push../node_modules/rxjs/_esm5/internal/Subscriber.js.Subscriber.next (http://localhost:8100/vendor.js:121614:18)
    at Notification.push../node_modules/rxjs/_esm5/internal/Notification.js.Notification.observe (http://localhost:8100/vendor.js:120879:50)
    at QueueAction.push../node_modules/rxjs/_esm5/internal/operators/observeOn.js.ObserveOnSubscriber.dispatch [as work] (http://localhost:8100/vendor.js:127241:22)
    at QueueAction.push../node_modules/rxjs/_esm5/internal/scheduler/AsyncAction.js.AsyncAction._execute (http://localhost:8100/vendor.js:131202:18)
    at QueueAction.push../node_modules/rxjs/_esm5/internal/scheduler/QueueAction.js.QueueAction.execute (http://localhost:8100/vendor.js:131350:18)
    at QueueScheduler.push../node_modules/rxjs/_esm5/internal/scheduler/AsyncScheduler.js.AsyncScheduler.flush (http://localhost:8100/vendor.js:131292:32)
    at QueueAction.push../node_modules/rxjs/_esm5/internal/scheduler/QueueAction.js.QueueAction.schedule (http://localhost:8100/vendor.js:131344:24)
    at QueueScheduler.push../node_modules/rxjs/_esm5/internal/Scheduler.js.Scheduler.schedule (http://localhost:8100/vendor.js:121304:53)
    at QueueScheduler.push../node_modules/rxjs/_esm5/internal/scheduler/AsyncScheduler.js.AsyncScheduler.schedule (http://localhost:8100/vendor.js:131280:46)
    at ObserveOnSubscriber.push../node_modules/rxjs/_esm5/internal/operators/observeOn.js.ObserveOnSubscriber.scheduleMessage (http://localhost:8100/vendor.js:127246:40)
    at ObserveOnSubscriber.push../node_modules/rxjs/_esm5/internal/operators/observeOn.js.ObserveOnSubscriber._next (http://localhost:8100/vendor.js:127249:14)
    at ObserveOnSubscriber.push../node_modules/rxjs/_esm5/internal/Subscriber.js.Subscriber.next (http://localhost:8100/vendor.js:121614:18)
    at MergeMapSubscriber.push../node_modules/rxjs/_esm5/internal/operators/mergeMap.js.MergeMapSubscriber.notifyNext (http://localhost:8100/vendor.js:126940:26)
    at InnerSubscriber.push../node_modules/rxjs/_esm5/internal/InnerSubscriber.js.InnerSubscriber._next (http://localhost:8100/vendor.js:120827:21)
    at InnerSubscriber.push../node_modules/rxjs/_esm5/internal/Subscriber.js.Subscriber.next (http://localhost:8100/vendor.js:121614:18)
    at MapSubscriber.push../node_modules/rxjs/_esm5/internal/operators/map.js.MapSubscriber._next (http://localhost:8100/vendor.js:126656:26)
    at MapSubscriber.push../node_modules/rxjs/_esm5/internal/Subscriber.js.Subscriber.next (http://localhost:8100/vendor.js:121614:18)
    at MergeMapSubscriber.push../node_modules/rxjs/_esm5/internal/operators/mergeMap.js.MergeMapSubscriber.notifyNext (http://localhost:8100/vendor.js:126940:26)
    at InnerSubscriber.push../node_modules/rxjs/_esm5/internal/InnerSubscriber.js.InnerSubscriber._next (http://localhost:8100/vendor.js:120827:21)
    at InnerSubscriber.push../node_modules/rxjs/_esm5/internal/Subscriber.js.Subscriber.next (http://localhost:8100/vendor.js:121614:18)
    at SkipSubscriber.push../node_modules/rxjs/_esm5/internal/operators/skip.js.SkipSubscriber._next (http://localhost:8100/vendor.js:128619:30)
    at SkipSubscriber.push../node_modules/rxjs/_esm5/internal/Subscriber.js.Subscriber.next (http://localhost:8100/vendor.js:121614:18)
    at ActionsSubject.push../node_modules/rxjs/_esm5/internal/Subject.js.Subject.next (http://localhost:8100/vendor.js:121380:25)
    at ActionsSubject.push../node_modules/rxjs/_esm5/internal/BehaviorSubject.js.BehaviorSubject.next (http://localhost:8100/vendor.js:120791:31)
    at ActionsSubject.push../node_modules/@ngrx/store/fesm5/store.js.ActionsSubject.next (http://localhost:8100/vendor.js:103818:31)
    at Store.push../node_modules/@ngrx/store/fesm5/store.js.Store.dispatch (http://localhost:8100/vendor.js:104118:30)
    at EmailFacade.push../node_modules/@briebug/ngrx-auto-entity/fesm5/briebug-ngrx-auto-entity.js.Facade.deselectMany (http://localhost:8100/vendor.js:86843:24)
    at SafeSubscriber._next (http://localhost:8100/main.js:4448:23)
    at SafeSubscriber.push../node_modules/rxjs/_esm5/internal/Subscriber.js.SafeSubscriber.__tryOrUnsub (http://localhost:8100/vendor.js:121753:16)
    at SafeSubscriber.push../node_modules/rxjs/_esm5/internal/Subscriber.js.SafeSubscriber.next (http://localhost:8100/vendor.js:121691:22)
    at Subscriber.push../node_modules/rxjs/_esm5/internal/Subscriber.js.Subscriber._next (http://localhost:8100/vendor.js:121637:26)
    at Subscriber.push../node_modules/rxjs/_esm5/internal/Subscriber.js.Subscriber.next (http://localhost:8100/vendor.js:121614:18)
    at ThrowIfEmptySubscriber.push../node_modules/rxjs/_esm5/internal/operators/throwIfEmpty.js.ThrowIfEmptySubscriber._next (http://localhost:8100/vendor.js:129655:26)
    at ThrowIfEmptySubscriber.push../node_modules/rxjs/_esm5/internal/Subscriber.js.Subscriber.next (http://localhost:8100/vendor.js:121614:18)
    at TakeSubscriber.push../node_modules/rxjs/_esm5/internal/operators/take.js.TakeSubscriber._next (http://localhost:8100/vendor.js:129082:30)
    at TakeSubscriber.push../node_modules/rxjs/_esm5/internal/Subscriber.js.Subscriber.next (http://localhost:8100/vendor.js:121614:18)
```

**Comment by jrista** [comment]
Thanks for the bug report, @richardshergold. Could you by chance share your entity model? Does it have a composite key?

**Comment by richardshergold** [comment]
```
export class Email {
  @Key _id: string;
  type: string;
  msg: string;
  regarding: string;
  subject: string;
  updatedTs: string;
  attachments: [];
  summary: string;
  authorId: number;
  authorName: string;
  authorImg: string;
  read: number;
  starred: number;
  archived: number;
  newItem: boolean;
}

```

**Comment by richardshergold** [comment]
This is what I am doing to toggle an item as selected or de-selected?  Should this work?

```
toggleSelect(item) {
    this.currentSetKeys$.pipe(take(1)).subscribe((keys: string[]) => {
      if (keys) {
        if (keys.includes(item._id)) {
          this.deselectMany([item]);
        } else {
          this.selectMore([item]);
        }
      } else {
        this.selectMany([item]);
      }
    });
  }
```

**Comment by jrista** [comment]
Hmm, at first glance, I am not sure it will. I will have to play with it a bit, but the way you have that coded now, I would think that you will only see something happen if currentSetKeys actually emits a new value. If it does not emit a value, then nothing will happen until it does. 

I think you may need to take a more reactive approach to this. At the very least, something along the lines of this:

```typescript
toggleSelect(item) {
    of(item).pipe(
        withLatestFrom(this.currentSetKeys$)
    ).subscribe(keys: string[] => 
        (keys && keys.includes(item._id)) ? this.deselectMany([item]) : this.selectMore([item])
    );
}
```

This may seem nuanced in terms of how it differs from your code, but the nuance may be necessary. By using `withLatestFrom`, you should be capturing the latest from the current set always. Now...this still requires `currentSetKeys$` to emit at least once. If it does not, then this will still not work. One of the quirks of reactive programming, I guess. 

I can think of some ways to get around that issue. For now I'll leave it as an exercise for the user. ;) There are a few ways I think you could probably handle this and ensure that even if you have never selected anything before, you can still get your toggle working. You could observe the `currentSetKeys$` for the first change, and when it happens set a private flag property on your facade to true. You could then check that flag to determine if you need to send an initial selectMany, or use the above code. That should only need to happen once, as once the first event moves through `currentSetKeys$` then from that point on `withLatestFrom` should work.

**Comment by jrista** [comment]
@richardshergold So looking at your model there. Can you help me understand where this entity key is coming from:

`100000080_organisations-email_592913`

Is that the actual key value of email._id?

**Comment by richardshergold** [comment]
Yes. That’s the id value.

**Comment by jrista** [comment]
@richardshergold I have identified the cause of this issue as well. I'll be rolling both fixes into a single PR soon here.
