### ISSUE TITLE
Fix: serialize `loadedAt`

### ISSUE THREAD

**Issue by schuchard** [briebug/ngrx-auto-entity#98]
with strict run time checks on:

```ts
runtimeChecks: {
  strictStateImmutability: true,
  strictActionImmutability: true,
  strictStateSerializability: true,
  strictActionSerializability: true,
},
```

an error is occasionally thrown, in my case when switch to another lazy module after this entity has been loaded

```
Error: Detected unserializable state at "queryContact.loadedAt"
    at throwIfUnserializable (http://localhost:4200/vendor.js:145543:19)
    at http://localhost:4200/vendor.js:145483:13
    at http://localhost:4200/vendor.js:145425:27
    at autoEntityReducer (http://localhost:4200/vendor.js:140459:12)
    at http://localhost:4200/vendor.js:140474:16
    at http://localhost:4200/vendor.js:144688:20
    at computeNextEntry (http://localhost:4200/vendor.js:143514:21)
    at recomputeStates (http://localhost:4200/vendor.js:143567:15)
    at http://localhost:4200/vendor.js:143915:26
    at ScanSubscriber.StoreDevtools.liftedAction$.pipe.Object.state [as accumulator] (http://localhost:4200/vendor.js:143967:38)
    at ScanSubscriber._tryNext (http://localhost:4200/vendor.js:200620:27)
    at ScanSubscriber._next (http://localhost:4200/vendor.js:200613:25)
    at ScanSubscriber.next (http://localhost:4200/vendor.js:194274:18)
    at WithLatestFromSubscriber._next (http://localhost:4200/vendor.js:202672:34)
    at WithLatestFromSubscriber.next (http://localhost:4200/vendor.js:194274:18)
    at Notification.observe (http://localhost:4200/vendor.js:193617:50)
    at QueueAction.dispatch [as work] (http://localhost:4200/vendor.js:199743:22)
    at QueueAction._execute (http://localhost:4200/vendor.js:202977:18)
    at QueueAction.execute (http://localhost:4200/vendor.js:203100:18)
    at QueueScheduler.flush (http://localhost:4200/vendor.js:203053:32)
    at QueueAction.schedule (http://localhost:4200/vendor.js:203094:24)
    at QueueScheduler.schedule (http://localhost:4200/vendor.js:193996:53)
    at QueueScheduler.schedule (http://localhost:4200/vendor.js:203041:26)
    at ObserveOnSubscriber.scheduleMessage (http://localhost:4200/vendor.js:199748:40)
    at ObserveOnSubscriber._next (http://localhost:4200/vendor.js:199751:14)
    at ObserveOnSubscriber.next (http://localhost:4200/vendor.js:194274:18)
    at MergeMapSubscriber.notifyNext (http://localhost:4200/vendor.js:199485:26)
    at InnerSubscriber._next (http://localhost:4200/vendor.js:193569:21)
    at InnerSubscriber.next (http://localhost:4200/vendor.js:194274:18)
    at MapSubscriber._next (http://localhost:4200/vendor.js:199249:26)
    at MapSubscriber.next (http://localhost:4200/vendor.js:194274:18)
    at MergeMapSubscriber.notifyNext (http://localhost:4200/vendor.js:199485:26)
    at InnerSubscriber._next (http://localhost:4200/vendor.js:193569:21)
    at InnerSubscriber.next (http://localhost:4200/vendor.js:194274:18)
    at SkipSubscriber._next (http://localhost:4200/vendor.js:200948:30)
    at SkipSubscriber.next (http://localhost:4200/vendor.js:194274:18)
    at ActionsSubject.next (http://localhost:4200/vendor.js:194060:25)
    at ActionsSubject.next (http://localhost:4200/vendor.js:193541:15)
    at ActionsSubject.next (http://localhost:4200/vendor.js:144478:15)
    at Store.dispatch (http://localhost:4200/vendor.js:145012:30)
    at StoreRouterConnectingModule.dispatchRouterAction (http://localhost:4200/vendor.js:142656:24)
    at StoreRouterConnectingModule.dispatchRouterRequest (http://localhost:4200/vendor.js:142600:14)
    at SafeSubscriber._next (http://localhost:4200/vendor.js:142566:26)
    at SafeSubscriber.__tryOrUnsub (http://localhost:4200/vendor.js:194410:16)
    at SafeSubscriber.next (http://localhost:4200/vendor.js:194349:22)
    at Subscriber._next (http://localhost:4200/vendor.js:194297:26)
    at Subscriber.next (http://localhost:4200/vendor.js:194274:18)
    at WithLatestFromSubscriber._next (http://localhost:4200/vendor.js:202672:34)
    at WithLatestFromSubscriber.next (http://localhost:4200/vendor.js:194274:18)
    at Subject.next (http://localhost:4200/vendor.js:194060:25)
    at SwitchMapSubscriber.project (http://localhost:4200/vendor.js:133635:39)
    at SwitchMapSubscriber._next (http://localhost:4200/vendor.js:201262:27)
    at SwitchMapSubscriber.next (http://localhost:4200/vendor.js:194274:18)
    at Observable._subscribe (http://localhost:4200/vendor.js:196491:20)
    at Observable._trySubscribe (http://localhost:4200/vendor.js:193730:25)
    at Observable.subscribe (http://localhost:4200/vendor.js:193716:22)
    at SwitchMapOperator.call (http://localhost:4200/vendor.js:201249:23)
    at Observable.subscribe (http://localhost:4200/vendor.js:193711:31)
    at SwitchMapOperator.call (http://localhost:4200/vendor.js:201249:23)
    at Observable.subscribe (http://localhost:4200/vendor.js:193711:31)
    at SwitchMapOperator.call (http://localhost:4200/vendor.js:201249:23)
    at Observable.subscribe (http://localhost:4200/vendor.js:193711:31)
    at DoOperator.call (http://localhost:4200/vendor.js:201593:23)
    at Observable.subscribe (http://localhost:4200/vendor.js:193711:31)
    at MergeMapOperator.call (http://localhost:4200/vendor.js:199437:23)
    at Observable.subscribe (http://localhost:4200/vendor.js:193711:31)
    at DoOperator.call (http://localhost:4200/vendor.js:201593:23)
    at Observable.subscribe (http://localhost:4200/vendor.js:193711:31)
    at DoOperator.call (http://localhost:4200/vendor.js:201593:23)
    at Observable.subscribe (http://localhost:4200/vendor.js:193711:31)
    at http://localhost:4200/vendor.js:203872:31
    at subscribeToResult (http://localhost:4200/vendor.js:204028:84)
    at SwitchMapSubscriber._innerSub (http://localhost:4200/vendor.js:201278:115)
    at SwitchMapSubscriber._next (http://localhost:4200/vendor.js:201268:14)
    at SwitchMapSubscriber.next (http://localhost:4200/vendor.js:194274:18)
    at TapSubscriber._next (http://localhost:4200/vendor.js:201623:26)
    at TapSubscriber.next (http://localhost:4200/vendor.js:194274:18)
    at Observable._subscribe (http://localhost:4200/vendor.js:196491:20)
    at Observable._trySubscribe (http://localhost:4200/vendor.js:193730:25)
    at Observable.subscribe (http://localhost:4200/vendor.js:193716:22)
    at DoOperator.call (http://localhost:4200/vendor.js:201593:23)
    at Observable.subscribe (http://localhost:4200/vendor.js:193711:31)
    at SwitchMapOperator.call (http://localhost:4200/vendor.js:201249:23)
    at Observable.subscribe (http://localhost:4200/vendor.js:193711:31)
    at SwitchMapOperator.call (http://localhost:4200/vendor.js:201249:23)
    at Observable.subscribe (http://localhost:4200/vendor.js:193711:31)
    at DoOperator.call (http://localhost:4200/vendor.js:201593:23)
    at Observable.subscribe (http://localhost:4200/vendor.js:193711:31)
    at MapOperator.call (http://localhost:4200/vendor.js:199230:23)
    at Observable.subscribe (http://localhost:4200/vendor.js:193711:31)
    at MergeMapOperator.call (http://localhost:4200/vendor.js:199437:23)
    at Observable.subscribe (http://localhost:4200/vendor.js:193711:31)
    at DoOperator.call (http://localhost:4200/vendor.js:201593:23)
    at Observable.subscribe (http://localhost:4200/vendor.js:193711:31)
    at DoOperator.call (http://localhost:4200/vendor.js:201593:23)
    at Observable.subscribe (http://localhost:4200/vendor.js:193711:31)
    at FilterOperator.call (http://localhost:4200/vendor.js:198742:23)
    at Observable.subscribe (http://localhost:4200/vendor.js:193711:31)
    at SwitchMapOperator.call (http://localhost:4200/vendor.js:201249:23)
    at Observable.subscribe (http://localhost:4200/vendor.js:193711:31)
    at SwitchMapOperator.call (http://localhost:4200/vendor.js:201249:23)
    at Observable.subscribe (http://localhost:4200/vendor.js:193711:31)
    at MapOperator.call (http://localhost:4200/vendor.js:199230:23)
    at Observable.subscribe (http://localhost:4200/vendor.js:193711:31)
    at DoOperator.call (http://localhost:4200/vendor.js:201593:23)
    at Observable.subscribe (http://localhost:4200/vendor.js:193711:31)
    at MapOperator.call (http://localhost:4200/vendor.js:199230:23)
    at Observable.subscribe (http://localhost:4200/vendor.js:193711:31)
    at DoOperator.call (http://localhost:4200/vendor.js:201593:23)
    at Observable.subscribe (http://localhost:4200/vendor.js:193711:31)
    at FinallyOperator.call (http://localhost:4200/vendor.js:198792:23)
    at Observable.subscribe (http://localhost:4200/vendor.js:193711:31)
    at CatchOperator.call (http://localhost:4200/vendor.js:197483:23)
    at Observable.subscribe (http://localhost:4200/vendor.js:193711:31)
    at http://localhost:4200/vendor.js:203872:31
    at subscribeToResult (http://localhost:4200/vendor.js:204028:84)
    at SwitchMapSubscriber._innerSub (http://localhost:4200/vendor.js:201278:115)
    at SwitchMapSubscriber._next (http://localhost:4200/vendor.js:201268:14)
    at SwitchMapSubscriber.next (http://localhost:4200/vendor.js:194274:18)
    at MapSubscriber._next (http://localhost:4200/vendor.js:199249:26)
    at MapSubscriber.next (http://localhost:4200/vendor.js:194274:18)
    at FilterSubscriber._next (http://localhost:4200/vendor.js:198762:30)
    at FilterSubscriber.next (http://localhost:4200/vendor.js:194274:18)
    at BehaviorSubject.next (http://localhost:4200/vendor.js:194060:25)
    at BehaviorSubject.next (http://localhost:4200/vendor.js:193541:15)
    at Router.setTransition (http://localhost:4200/vendor.js:133966:26)
    at Router.scheduleNavigation (http://localhost:4200/vendor.js:134328:14)
    at Router.navigateByUrl (http://localhost:4200/vendor.js:134165:21)
    at RouterLink.onClick (http://localhost:4200/vendor.js:134547:21)
    at Object.eval [as handleEvent] (ng:///HomePagesModule/HomePageComponent.ngfactory.js:156:41)
    at handleEvent (http://localhost:4200/vendor.js:98516:122)
    at callWithDebugContext (http://localhost:4200/vendor.js:100135:27)
    at Object.debugHandleEvent [as handleEvent] (http://localhost:4200/vendor.js:99770:12)
    at dispatchEvent (http://localhost:4200/vendor.js:85603:25)
    at http://localhost:4200/vendor.js:97448:16
    at HTMLButtonElement.<anonymous> (http://localhost:4200/vendor.js:125406:38)
    at ZoneDelegate.invokeTask (http://localhost:4200/polyfills.js:3626:31)
    at Object.onInvokeTask (http://localhost:4200/vendor.js:94519:33)
    at ZoneDelegate.invokeTask (http://localhost:4200/polyfills.js:3625:60)
    at Zone.runTask (http://localhost:4200/polyfills.js:3403:47)
    at ZoneTask.invokeTask [as invoke] (http://localhost:4200/polyfills.js:3700:34)
    at invokeTask (http://localhost:4200/polyfills.js:4838:14)
    at HTMLButtonElement.globalZoneAwareCallback (http://localhost:4200/polyfills.js:4864:17)
```

**Comment by schuchard** [comment]
`loadedAt` is set as a Date object which is not serializeable, perhaps `toISOString()` is called for here.

**Comment by jrista** [comment]
Thanks for the bug report, @schuchard! I think what we can do, is store the **unix time** in state. The existing selectors can then generate a `Date` object from that unix time, which would make the change largely internal. That should maintain compatibility with most existing users of the library.

The only case where it _might_ be a breaking change, would be for anyone writing their own selectors directly off of state. Hopefully no one is actually doing that, and is instead using either the existing selectors or facade getters to retrieve this data from auto-entity managed state.
